// Code generated by go-swagger; DO NOT EDIT.

package actor

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"filmoteka_server/models"
)

// AddActorHandlerFunc turns a function with the right signature into a add actor handler
type AddActorHandlerFunc func(AddActorParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn AddActorHandlerFunc) Handle(params AddActorParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// AddActorHandler interface for that can handle valid add actor params
type AddActorHandler interface {
	Handle(AddActorParams, *models.Principal) middleware.Responder
}

// NewAddActor creates a new http.Handler for the add actor operation
func NewAddActor(ctx *middleware.Context, handler AddActorHandler) *AddActor {
	return &AddActor{Context: ctx, Handler: handler}
}

/*
	AddActor swagger:route POST /actors Actor addActor

Добавить актера
*/
type AddActor struct {
	Context *middleware.Context
	Handler AddActorHandler
}

func (o *AddActor) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewAddActorParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
