// Code generated by go-swagger; DO NOT EDIT.

package actor

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// AddActorOKCode is the HTTP code returned for type AddActorOK
const AddActorOKCode int = 200

/*
AddActorOK Успешно

swagger:response addActorOK
*/
type AddActorOK struct {
}

// NewAddActorOK creates AddActorOK with default headers values
func NewAddActorOK() *AddActorOK {

	return &AddActorOK{}
}

// WriteResponse to the client
func (o *AddActorOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// AddActorBadRequestCode is the HTTP code returned for type AddActorBadRequest
const AddActorBadRequestCode int = 400

/*
AddActorBadRequest Ошибка

swagger:response addActorBadRequest
*/
type AddActorBadRequest struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewAddActorBadRequest creates AddActorBadRequest with default headers values
func NewAddActorBadRequest() *AddActorBadRequest {

	return &AddActorBadRequest{}
}

// WithPayload adds the payload to the add actor bad request response
func (o *AddActorBadRequest) WithPayload(payload string) *AddActorBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the add actor bad request response
func (o *AddActorBadRequest) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *AddActorBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
