// Code generated by go-swagger; DO NOT EDIT.

package actor

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"filmoteka_server/models"
)

// DeleteActorHandlerFunc turns a function with the right signature into a delete actor handler
type DeleteActorHandlerFunc func(DeleteActorParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteActorHandlerFunc) Handle(params DeleteActorParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// DeleteActorHandler interface for that can handle valid delete actor params
type DeleteActorHandler interface {
	Handle(DeleteActorParams, *models.Principal) middleware.Responder
}

// NewDeleteActor creates a new http.Handler for the delete actor operation
func NewDeleteActor(ctx *middleware.Context, handler DeleteActorHandler) *DeleteActor {
	return &DeleteActor{Context: ctx, Handler: handler}
}

/*
	DeleteActor swagger:route DELETE /actors Actor deleteActor

Удалить запись об актере
*/
type DeleteActor struct {
	Context *middleware.Context
	Handler DeleteActorHandler
}

func (o *DeleteActor) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewDeleteActorParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
