// Code generated by go-swagger; DO NOT EDIT.

package actor

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// UpdateActorOKCode is the HTTP code returned for type UpdateActorOK
const UpdateActorOKCode int = 200

/*
UpdateActorOK Обновлено удачно

swagger:response updateActorOK
*/
type UpdateActorOK struct {
}

// NewUpdateActorOK creates UpdateActorOK with default headers values
func NewUpdateActorOK() *UpdateActorOK {

	return &UpdateActorOK{}
}

// WriteResponse to the client
func (o *UpdateActorOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// UpdateActorBadRequestCode is the HTTP code returned for type UpdateActorBadRequest
const UpdateActorBadRequestCode int = 400

/*
UpdateActorBadRequest Ошибка

swagger:response updateActorBadRequest
*/
type UpdateActorBadRequest struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewUpdateActorBadRequest creates UpdateActorBadRequest with default headers values
func NewUpdateActorBadRequest() *UpdateActorBadRequest {

	return &UpdateActorBadRequest{}
}

// WithPayload adds the payload to the update actor bad request response
func (o *UpdateActorBadRequest) WithPayload(payload string) *UpdateActorBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update actor bad request response
func (o *UpdateActorBadRequest) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateActorBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
