// Code generated by go-swagger; DO NOT EDIT.

package film

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"filmoteka_server/models"
)

// AddFilmHandlerFunc turns a function with the right signature into a add film handler
type AddFilmHandlerFunc func(AddFilmParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn AddFilmHandlerFunc) Handle(params AddFilmParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// AddFilmHandler interface for that can handle valid add film params
type AddFilmHandler interface {
	Handle(AddFilmParams, *models.Principal) middleware.Responder
}

// NewAddFilm creates a new http.Handler for the add film operation
func NewAddFilm(ctx *middleware.Context, handler AddFilmHandler) *AddFilm {
	return &AddFilm{Context: ctx, Handler: handler}
}

/*
	AddFilm swagger:route POST /films Film addFilm

Добавить фильм
*/
type AddFilm struct {
	Context *middleware.Context
	Handler AddFilmHandler
}

func (o *AddFilm) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewAddFilmParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
