// Code generated by go-swagger; DO NOT EDIT.

package film

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"filmoteka_server/models"
)

// DeleteFilmHandlerFunc turns a function with the right signature into a delete film handler
type DeleteFilmHandlerFunc func(DeleteFilmParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteFilmHandlerFunc) Handle(params DeleteFilmParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// DeleteFilmHandler interface for that can handle valid delete film params
type DeleteFilmHandler interface {
	Handle(DeleteFilmParams, *models.Principal) middleware.Responder
}

// NewDeleteFilm creates a new http.Handler for the delete film operation
func NewDeleteFilm(ctx *middleware.Context, handler DeleteFilmHandler) *DeleteFilm {
	return &DeleteFilm{Context: ctx, Handler: handler}
}

/*
	DeleteFilm swagger:route DELETE /films Film deleteFilm

Удалить запись о фильме
*/
type DeleteFilm struct {
	Context *middleware.Context
	Handler DeleteFilmHandler
}

func (o *DeleteFilm) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewDeleteFilmParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
