// Code generated by go-swagger; DO NOT EDIT.

package film

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// DeleteFilmNoContentCode is the HTTP code returned for type DeleteFilmNoContent
const DeleteFilmNoContentCode int = 204

/*
DeleteFilmNoContent Успешное удаление

swagger:response deleteFilmNoContent
*/
type DeleteFilmNoContent struct {
}

// NewDeleteFilmNoContent creates DeleteFilmNoContent with default headers values
func NewDeleteFilmNoContent() *DeleteFilmNoContent {

	return &DeleteFilmNoContent{}
}

// WriteResponse to the client
func (o *DeleteFilmNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

// DeleteFilmBadRequestCode is the HTTP code returned for type DeleteFilmBadRequest
const DeleteFilmBadRequestCode int = 400

/*
DeleteFilmBadRequest Некорректные входные данные

swagger:response deleteFilmBadRequest
*/
type DeleteFilmBadRequest struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewDeleteFilmBadRequest creates DeleteFilmBadRequest with default headers values
func NewDeleteFilmBadRequest() *DeleteFilmBadRequest {

	return &DeleteFilmBadRequest{}
}

// WithPayload adds the payload to the delete film bad request response
func (o *DeleteFilmBadRequest) WithPayload(payload string) *DeleteFilmBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete film bad request response
func (o *DeleteFilmBadRequest) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteFilmBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
