// Code generated by go-swagger; DO NOT EDIT.

package film

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"errors"
	"net/url"
	golangswaggerpaths "path"
)

// FindFilmURL generates an URL for the find film operation
type FindFilmURL struct {
	Actor string
	Desc  string

	_basePath string
	// avoid unkeyed usage
	_ struct{}
}

// WithBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *FindFilmURL) WithBasePath(bp string) *FindFilmURL {
	o.SetBasePath(bp)
	return o
}

// SetBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *FindFilmURL) SetBasePath(bp string) {
	o._basePath = bp
}

// Build a url path and query string
func (o *FindFilmURL) Build() (*url.URL, error) {
	var _result url.URL

	var _path = "/films/find"

	_basePath := o._basePath
	if _basePath == "" {
		_basePath = "/Filmoteka/"
	}
	_result.Path = golangswaggerpaths.Join(_basePath, _path)

	qs := make(url.Values)

	actorQ := o.Actor
	if actorQ != "" {
		qs.Set("actor", actorQ)
	}

	descQ := o.Desc
	if descQ != "" {
		qs.Set("desc", descQ)
	}

	_result.RawQuery = qs.Encode()

	return &_result, nil
}

// Must is a helper function to panic when the url builder returns an error
func (o *FindFilmURL) Must(u *url.URL, err error) *url.URL {
	if err != nil {
		panic(err)
	}
	if u == nil {
		panic("url can't be nil")
	}
	return u
}

// String returns the string representation of the path with query string
func (o *FindFilmURL) String() string {
	return o.Must(o.Build()).String()
}

// BuildFull builds a full url with scheme, host, path and query string
func (o *FindFilmURL) BuildFull(scheme, host string) (*url.URL, error) {
	if scheme == "" {
		return nil, errors.New("scheme is required for a full url on FindFilmURL")
	}
	if host == "" {
		return nil, errors.New("host is required for a full url on FindFilmURL")
	}

	base, err := o.Build()
	if err != nil {
		return nil, err
	}

	base.Scheme = scheme
	base.Host = host
	return base, nil
}

// StringFull returns the string representation of a complete url
func (o *FindFilmURL) StringFull(scheme, host string) string {
	return o.Must(o.BuildFull(scheme, host)).String()
}
