// Code generated by go-swagger; DO NOT EDIT.

package film

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// NewGetAllFilmsSortedParams creates a new GetAllFilmsSortedParams object
// with the default values initialized.
func NewGetAllFilmsSortedParams() GetAllFilmsSortedParams {

	var (
		// initialize parameters with default values

		sortByDefault = string("rating")
	)

	return GetAllFilmsSortedParams{
		SortBy: &sortByDefault,
	}
}

// GetAllFilmsSortedParams contains all the bound params for the get all films sorted operation
// typically these are obtained from a http.Request
//
// swagger:parameters getAllFilmsSorted
type GetAllFilmsSortedParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*
	  In: query
	  Default: "rating"
	*/
	SortBy *string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetAllFilmsSortedParams() beforehand.
func (o *GetAllFilmsSortedParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	qs := runtime.Values(r.URL.Query())

	qSortBy, qhkSortBy, _ := qs.GetOK("sortBy")
	if err := o.bindSortBy(qSortBy, qhkSortBy, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindSortBy binds and validates parameter SortBy from query.
func (o *GetAllFilmsSortedParams) bindSortBy(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false

	if raw == "" { // empty values pass all other validations
		// Default values have been previously initialized by NewGetAllFilmsSortedParams()
		return nil
	}
	o.SortBy = &raw

	if err := o.validateSortBy(formats); err != nil {
		return err
	}

	return nil
}

// validateSortBy carries on validations for parameter SortBy
func (o *GetAllFilmsSortedParams) validateSortBy(formats strfmt.Registry) error {

	if err := validate.EnumCase("sortBy", "query", *o.SortBy, []interface{}{"title", "rating", "datepremiere"}, true); err != nil {
		return err
	}

	return nil
}
