// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// UserLoginOKCode is the HTTP code returned for type UserLoginOK
const UserLoginOKCode int = 200

/*
UserLoginOK Успешнный вход в систему

swagger:response userLoginOK
*/
type UserLoginOK struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewUserLoginOK creates UserLoginOK with default headers values
func NewUserLoginOK() *UserLoginOK {

	return &UserLoginOK{}
}

// WithPayload adds the payload to the user login o k response
func (o *UserLoginOK) WithPayload(payload string) *UserLoginOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the user login o k response
func (o *UserLoginOK) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UserLoginOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// UserLoginBadRequestCode is the HTTP code returned for type UserLoginBadRequest
const UserLoginBadRequestCode int = 400

/*
UserLoginBadRequest Неверное имя пользователя / пароль

swagger:response userLoginBadRequest
*/
type UserLoginBadRequest struct {
}

// NewUserLoginBadRequest creates UserLoginBadRequest with default headers values
func NewUserLoginBadRequest() *UserLoginBadRequest {

	return &UserLoginBadRequest{}
}

// WriteResponse to the client
func (o *UserLoginBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}
